name = "signage-pwa"
type = "javascript"

[env.production]
workers_dev = false
compatibility_date = "2025-03-28"
account_id = "bfae875f0457ce7d595f0d23a897e5c9"
workers_namespace = "21abd14b95c42bf8aea88e7d023c0d62"
route = "gravefury.com/*"
zone_id = "5bf7aa1aacbc2fc5fb3472d55467ea29"

[env.dev]
workers_dev = true
compatibility_date = "2025-03-28"
account_id = "bfae875f0457ce7d595f0d23a897e5c9"
workers_namespace = "073c9f84634507a25dd9df0309264d"
route = ""
zone_id = ""

[build]
command = "npm run build"

[deploy]
commit = true
